language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 HOME
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'


script: "git reset --hard ; ./gradlew clean build"


before_deploy:
  - zip -r springstudy *
  - mkdir -p deploy
  - mv springstudy.zip deploy/springstudy.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis에 설정된 아이디값
    secret_access_key: $AWS_SECRET_KEY  # Travis에 설정된 비밀값
    bucket: spring-study-build
    region: ap-northeast-2
    acl: private
    local_dir: deploy
    wait-until-deployed: true

# CI 실행완료시 메일로 알림
notifications:
  email:
    recipients:
      - jm97010412@gmail.com